services:

  web:
    build: .
    container_name: employee_django
    command: gunicorn employee_mgmt.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: employee_mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employee_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot_password"
        ]
      timeout: 5s
      retries: 10
      interval: 5s

volumes:
  mysql_data: